# https://www.codedisciples.in/travis-postgres.html

language: python
python:
  - '3.6.9'
install:
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - python -m unittest discover -v -s tests/ -p '*_tests.py'

before_script:
  - psql -c 'create database gefiproj;' -U postgres
