do $$
DECLARE
	nom_nveau_financeur varchar;
	financeurs varchar[] := array['AERMC','OFB','ARBE','CBNMC','CC UBAYE','CDC','CEN 73','CFPPA-UFA TERRE D''HORIZON','CNRS','EYZIN-PINET','CD 01','CD 04','CD 05','CD 26','CD 38','CD 73','CD 74','REGION PACA','REGION AURA','CONSERVATOIRE DU LITTORAL','CPAM','CREA','CREA','DDT 05','DIRCE','DIRMED','DRAAF AURA','DREAL PACA','DREAL AURA','EARL MICHEL OGIER','ECOCEAN','EDF SA','FEDER MASSIF','FEDER ALCOTRA','FEDER FS','FEDER RA','FNADT','GAP','GYPSE DE MAURIENNE','INRAE','LA ROMANS','LELY ENVIRONNEMENT','UNITHEQUE','MAIF','MINISTERE ECOLOGIE','MNHN','ONF','PARC NATIONAL DE LA VANOISE','PARC NATIONAL DU MERCANTOUR','PLEFPA TERRE D''HORIZON','PNR DE CHARTREUSE','PNR DES BAUGES','PNR DU LUBERON','PNR DU QUEYRAS','PNR DU QUEYRAS','PNR DES BARONNIES PROVENCALES','RTE','SATA','SCEA SERINES D''OR','SHR','SIVOM des SAISIES','SOFAXIS','TELT'];
BEGIN
	FOREACH nom_nveau_financeur IN ARRAY financeurs
   		LOOP
	  		RAISE NOTICE 'Financeur = %', nom_nveau_financeur;
			IF (SELECT id_financeur FROM financeur WHERE UPPER(nom_financeur) = UPPER(nom_nveau_financeur)) IS NULL THEN
				INSERT INTO financeur(id_financeur, nom_financeur, ref_arret_attributif_financeur)
					VALUES (DEFAULT, nom_nveau_financeur, '');
			END IF;
		END LOOP;
END $$